### ISSUE TITLE
[Android] Native Events are not emitted to JS

### ISSUE THREAD

**Issue by AlexanderPodlesniyQs** [voxeet/voxeet-uxkit-reactnative#6] opened 2020-04-28 06:35 UTC
**Native Events are not emitted to JS on Android**

After some research I've found 3 issues preventing event emitting.
1. RNVoxeetConferencekitPackage doesn't export RNVoxeetConferenceEventModule.
2. ConferenceStatusEventEmitter class doesn't have @Subscribe decorators for onEvent functions (ConferenceUserEventEmitter class has it).
3. AbstractEventEmitter class in emit function throws "InvocationTargetException: Map already consumed" exception. There are two events shoud be emitted, but because of this exception nothing it emitted.

I found solutions for all three above reasons. Maybe they are not best.
1, 2 are quite obvious: add module to export and add @Subscribe decorators.
3. I've add replaced map object usage with map.copy()

`context.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                .emit(callback.name(), map.copy());`

After these changes DeviceEventEmitter started to receive Voxeet events.

**Comment by codlab** [comment] 2020-04-28 06:37
This is not a bug, it's a feature meant to be released for a future version of the library 👍

**Comment by jchang0419** [comment] 2020-07-30 00:43
@codlab was this ever added?

**Comment by codlab** [comment] 2021-05-24 05:46
Closing this rather old ticket since it's now officially supported, almost every events are available. If some are missing (or will come but aren't yet), please open a new ticket 👍

**Closed by codlab** 2021-05-24 05:46 UTC
Labels: enhancement
