### ISSUE TITLE
not receiving voxeet events 

### ISSUE THREAD

**Issue by telltokichu** [voxeet/voxeet-uxkit-reactnative#24] opened 2021-04-02 08:37 UTC
@FabienLavocat  
I want to subscribe to voxeet events as mentioned in README.md

version i'm using 
    "@voxeet/react-native-voxeet-conferencekit": "^0.2.10",

```
import { VoxeetSDK } from "@voxeet/react-native-voxeet-conferencekit";
import { ConferenceStatusUpdatedEvent } from "@voxeet/react-native-voxeet-conferencekit";

const onConferenceStatus = (event: ConferenceStatusUpdatedEvent) => {
  console.warn("event received", event);
}

VoxeetSDK.events.addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
```

I am getting error - "[TypeError: Cannot read property 'addListener' of undefined]"
my code - 
```
  const isInitialized = await VoxeetSDK.initializeToken(data.access_token, refreshToken);
                    if (isInitialized) {
                        console.log("1 - Initialized");
                        VoxeetSDK.events.addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
                        const isSessionOpned = await VoxeetSDK.connect(userInfo);
                        console.log("2 - Session Opened", isSessionOpned);
                        if (isSessionOpned) {
```
other than that video conference is working fine.

**Comment by codlab** [comment] 2021-04-02 08:43
There’s a typo in the documentation. You actually need to use VoxeetSDK.events().addListener

**Comment by telltokichu** [comment] 2021-04-02 08:50
I updated it to 
```
                        VoxeetSDK.events().addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
```
still getting error - "[TypeError: undefined is not a function]"

**Comment by codlab** [comment] 2021-04-02 10:17
My bad, forgot that we set up a get events() which translates to a field access.

I can't reproduce the issue, can you copy paste the file at `node_modules/@voxeet/react-native-voxeet-conferencekit/dist/VoxeetSDK.js` from your project ?

**Comment by telltokichu** [comment] 2021-04-02 10:24
the file at node_modules/@voxeet/react-native-voxeet-conferencekit/dist/VoxeetSDK.js
```
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, privateMap) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to get private field on non-instance");
    }
    return privateMap.get(receiver);
};
var _events;
import { DeviceEventEmitter, NativeEventEmitter, NativeModules, Platform } from 'react-native';
import VoxeetEvents from './VoxeetEvents';
const { RNVoxeetConferencekit } = NativeModules;
;
;
export default class _VoxeetSDK {
    constructor() {
        _events.set(this, new VoxeetEvents());
        this.refreshAccessTokenCallback = null;
    }
    get events() { return __classPrivateFieldGet(this, _events); }
    set events(any) { }
    /**
     * Initializes the SDK using the customer key and secret.
     * @param consumerKey Consumer Key
     * @param consumerSecret Consumer Secret
     */
    initialize(consumerKey, consumerSecret) {
        return RNVoxeetConferencekit.initialize(consumerKey, consumerSecret);
    }
    /**
     * Initializes the SDK with an access token that is provided by the customer backend communicating with Voxeet servers.
     * @param accessToken Access token
     * @param refreshToken Callback to get a new access token after it expires
     */
    initializeToken(accessToken, refreshToken) {
        if (!this.refreshAccessTokenCallback) {
            this.refreshAccessTokenCallback = () => {
                refreshToken()
                    .then(token => RNVoxeetConferencekit.onAccessTokenOk(token))
                    .catch(err => {
                    RNVoxeetConferencekit.onAccessTokenKo("Token retrieval error");
                });
            };
            const eventEmitter = Platform.OS == "android" ? DeviceEventEmitter : new NativeEventEmitter(RNVoxeetConferencekit);
            eventEmitter.addListener("refreshToken", (e) => {
                this.refreshAccessTokenCallback && this.refreshAccessTokenCallback();
            });
        }
        return RNVoxeetConferencekit.initializeToken(accessToken);
    }
    /**
     * Opens a new session.
     * @param userInfo Participant information
     */
    connect(userInfo) {
        return RNVoxeetConferencekit.connect(userInfo);
    }
    /**
     * Closes the current session.
     */
    disconnect() {
        return RNVoxeetConferencekit.disconnect();
    }
    /**
     * Creates a conference.
     * @param options Options to use to create the conference
     */
    create(options) {
        return RNVoxeetConferencekit.create(options);
    }
    /**
     * Joins the conference.
     * @param conferenceId Id of the conference to join
     * @param options Options to use to join the conference
     */
    join(conferenceId, options = {}) {
        return RNVoxeetConferencekit.join(conferenceId, options);
    }
    /**
     * Leaves the conference.
     */
    leave() {
        return RNVoxeetConferencekit.leave();
    }
    /**
     * Invite a participant to the conference.
     * @param conferenceId Id of the conference to invite the participant to
     * @param participants List of participants to invite
     */
    invite(conferenceId, participants) {
        return RNVoxeetConferencekit.invite(conferenceId, participants);
    }
    /**
     * Sends a broadcast message to the participants of the conference.
     * @param message Message to send to the other participants
     */
    sendBroadcastMessage(message) {
        return RNVoxeetConferencekit.sendBroadcastMessage(message);
    }
    /**
     * Is telecom mode enabled.
     */
    isTelecomMode() {
        return RNVoxeetConferencekit.isTelecomMode();
    }
    /**
     * Is audio 3D enabled.
     */
    isAudio3DEnabled() {
        return RNVoxeetConferencekit.isAudio3DEnabled();
    }
    /**
     * Sets if you want the UXKit to appear maximized or not.
     * @param maximized True to have the UXKit to appear maximized
     */
    appearMaximized(maximized) {
        RNVoxeetConferencekit.appearMaximized(maximized);
        return true;
    }
    /**
     * Use the built in speaker by default.
     * @param enable True to use the built in speaker by default
     */
    defaultBuiltInSpeaker(enable) {
        RNVoxeetConferencekit.defaultBuiltInSpeaker(enable);
        return true;
    }
    /**
     * Sets the video on by default.
     * @param enable True to turn on the video by default
     */
    defaultVideo(enable) {
        RNVoxeetConferencekit.defaultVideo(enable);
        return true;
    }
    /**
     * Activates or disable the screen auto lock. Android only.
     * @param activate True to activate the screen auto lock
     */
    screenAutoLock(activate) {
        if (Platform.OS == "android") {
            RNVoxeetConferencekit.screenAutoLock(activate);
        }
    }
    /** @deprecated */
    isUserLoggedIn() {
        return RNVoxeetConferencekit.isUserLoggedIn();
    }
    /**
     * Checks if a conference is awaiting. Android only.
     */
    checkForAwaitingConference() {
        if (Platform.OS != "android")
            return new Promise(r => r(false));
        return RNVoxeetConferencekit.checkForAwaitingConference();
    }
    /** @deprecated Use join() instead. */
    startConference(conferenceId, participants) {
        return RNVoxeetConferencekit.startConference(conferenceId, participants);
    }
    /** @deprecated Use leave() instead. */
    stopConference() {
        return this.leave();
    }
    /** @deprecated Use connect() instead. */
    openSession(userInfo) {
        return this.connect(userInfo);
    }
    /** @deprecated Use disconnect() instead. */
    closeSession() {
        return this.disconnect();
    }
}
_events = new WeakMap();
export const VoxeetSDK = new _VoxeetSDK();
//# sourceMappingURL=VoxeetSDK.js.map
```

**Comment by codlab** [comment] 2021-04-02 10:26
What is your react native version?

**Comment by telltokichu** [comment] 2021-04-02 11:32
React native version 
```
"react-native": "0.63.4",
```

**Comment by codlab** [comment] 2021-04-04 10:39
Did you make sure that the cache was clean? Using `react-native start --reset-cache` should do it

**Comment by telltokichu** [comment] 2021-04-05 03:33
I ran with ```react-native start --reset-cache``` 

now i'm getting error stating - "**[TypeError: Object is not a function]**"

**Comment by codlab** [comment] 2021-04-05 11:28
Perfect, so you can use events as a field and not a function 👍

**Comment by telltokichu** [comment] 2021-04-07 08:55
could you please share code snippet ? 

current code :  from this which part should be updated ?
```
 const onConferenceStatus = (event) => {
          console.warn("event received", event);
      }

      VoxeetSDK.events().addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
```

**Comment by codlab** [comment] 2021-04-07 09:33
You can use this

```
 const onConferenceStatus = (event) => {
  console.warn("event received", event);
}

VoxeetSDK.events.addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
```

**Comment by chatwithsrini** [comment] 2021-04-08 06:40
i have used above.. it does not work.. it doesn't show error, but i din't receive events in console. i have used this on two different places

1. useEffect(() => {
    VoxeetSDK.events.addListener(ConferenceStatusUpdatedEvent, onConferenceStatus);
      }, []);

2. const isInitialized = await VoxeetSDK.initializeToken(data.access_token, refreshToken);
          if (isInitialized) {
            console.log("1 - Initialized");
            VoxeetSDK.events.addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
            const isSessionOpned = await VoxeetSDK.connect(userInfo);

**Comment by codlab** [comment] 2021-04-19 12:02
Using the develop, branch the event should be working as expected. Can you confirm?

**Comment by chatwithsrini** [comment] 2021-04-19 12:07
No logs and warns were printed in console. It simply do nothing... I didn't receive any events..

**Comment by codlab** [comment] 2021-04-19 12:07
The branch has been updated during the last few days, please check using the latest revision

**Comment by chatwithsrini** [comment] 2021-04-21 15:00
I have tried latest version of codes. There were no logs printed, when I toggles the function buttons on video call screen... Can you please provide sample code for events..

**Comment by codlab** [comment] 2021-04-22 08:02
The latest `git://github.com/voxeet/voxeet-uxkit-reactnative.git#develop` fix the issue 👍

**Comment by chatwithsrini** [comment] 2021-04-23 03:36
here i can see different types of events.. my actual problem is "I cant able to trigger events with above mentioned code". when i try addListener, it does not show any event. kidly suggest me to trigger event. 

This is the code i have used to initiate events:-

const onConferenceStatus = (event) => {
    console.warn("event received", event);
  }

   const isInitialized = await VoxeetSDK.initializeToken(data.access_token, refreshToken);
          VoxeetSDK.events.addListener("ConferenceStatusUpdatedEvent", onConferenceStatus);
          if (isInitialized) {
            console.log("1 - Initialized");
            VoxeetSDK.defaultVideo(true);
            const isSessionOpned = await VoxeetSDK.connect(userInfo);
            console.log("2 - Session Opened", isSessionOpned);
            if (isSessionOpned) {
              VoxeetSDK.create({ alias: videoChatSession.conferenceId }).then((conference) => {
                console.log('3 - conference Data', conference);
                VoxeetSDK.join(conference.conferenceId, joinOptions).then((response) => {
                  console.log('4 - Join Response => ', response);
               }).catch((err) => {
                  console.log('💎 ~ file: index.js ~ line 53 ~ err', err);
                })
              })
            }
          }

**Comment by chatwithsrini** [comment] 2021-04-23 05:45
i have tried devlop branch code. we have received events **successfully**..

could you please tell when you will publish this latest changes to @voxeet/react-native-voxeet-conferencekit package?

it will be really helpful, if these chenges are integrated as we are using it in our production application

**Comment by codlab** [comment] 2021-04-23 05:49
A new version will be pushed early next week. In the meantime, since lots of modification have been pushed in this branch, it should give you enough time to test and prevent any issue in your production app. I’m thinking about the new embedded version of the SDK (iOS and Android) as well as the push notification (Android) if you’re using them

**Comment by chatwithsrini** [comment] 2021-04-23 05:56
as we are fully dependent on react-native framework. we will wait for the new version next week... 

**thanks for your kind support, it is really helpful..**

**Comment by telltokichu** [comment] 2021-04-23 06:23
@codlab I can also see Events after sync up with develop branch code.
as you mentioned, looking forward next week for the new Version @voxeet/react-native-voxeet-conferencekit package.

Thanks a lot !

**Comment by codlab** [comment] 2021-05-24 05:43
A new version was pushed, a new one will follow quite soon (I still need to prepare a plan to have regular versions available in the future using a pre defined release window). I'm closing this ticket 👍

**Closed by codlab** 2021-05-24 05:43 UTC
Labels: bug
