### ISSUE TITLE
Crash in debug mode and random crash in release mode apk

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative#33] opened 2021-05-13 05:34 UTC
@codlab There crash we discussed on call while working with the debug builds is also occurring now with the release apk on random basis when the UI is displayed .
"react-native": "0.63.3"
"@voxeet/react-native-voxeet-conferencekit": "git://github.com/voxeet/voxeet-uxkit-reactnative.git#develop"
"@voxeet/react-native-voxeet-firebase": "^2.0.2"
It occurs randomly not everytime like it may work 2 times and on 3rd time it may crash .
I am attaching the screenshots and log file for your reference
![image](https://user-images.githubusercontent.com/72122766/118082189-5974c780-b3da-11eb-94e9-aa0911bee020.png)
![image](https://user-images.githubusercontent.com/72122766/118082200-5e397b80-b3da-11eb-9ee6-e049fc37da04.png)
![image](https://user-images.githubusercontent.com/72122766/118082211-61346c00-b3da-11eb-85c2-ca1227be7c9b.png)
[releaseCrashLog.txt](https://github.com/voxeet/voxeet-uxkit-reactnative/files/6470530/releaseCrashLog.txt)

**Comment by codlab** [comment] 2021-05-13 08:17
Did you properly configured the project?

**Comment by tuneerclixlogix** [comment] 2021-05-13 08:20
Yes, I followed all the steps and also checked the new changes in readme file. We have also noticed this issue on our last call but then it was happening only with the debug builds

**Comment by codlab** [comment] 2021-05-13 09:08
It would be great that if you can reproduce the release build crash, you send me an apk at my email kevin.leperf /a/ dolby.com

In on other note, I'm not familiar with react native 0.63.x since I bumped the various environment from pre <0.60 to 0.60.x, 0.61.x and 0.64.0 versions of react native. It is completely possible that 0.63.x has a random behavior.

Given 0.64.0, what I could reproduce is that opening the app in release mode is always consistant with a crash-free experience. In the 0.60 and 0.61, a side project I had fixed for debug (and release) the crashes using the following external "fix" : https://github.com/LNP-BP/react_native_demo/commit/96a5e4e92e500b51b4a422a70c7c456d400d401d

This basically removes debug dependencies onto a debugging library which also have release side effects, definitely worth giving a look at it (I will also try with the 0.64.0 test app as well - I will had a 0.63.0 branch in the following hours)

**Comment by tuneerclixlogix** [comment] 2021-05-13 11:32
Sure @codlab , I will create dummy accounts and will create an apk for you. I have also increased the react native version to 0.64.1 but still facing this crash. I have noticed that mostly it will occur when the application was in killed state and then someone calls but not everytime . And in debug mode it occurs everytime i start the conference

**Comment by codlab** [comment] 2021-05-13 18:51
I may have a complete working and reliable implementation in the test app. I was wandering around the ReactNative + Facebook implementation and tested to reintegrate the modification regarding debug mode.

With above modification + complete clean, it was working better but not enough, what I did was to also edit how the fbjni was loaded to remove it

Please take a look at and follow those modifications as well :

https://github.com/voxeet/voxeet-uxkit-reactnative-testapp/commit/894d10363ede47b1fcd2ae032e09a07c140f8f4c

You should normally follow those :

- make sure you were using Hermes engine (from the readme and such)
- in your android/app/build.gradle, exclude the fbjni-java-only
- remove the debugImplementation declarations
- remove the file (up to the folder "java", keep the manifest !)  android/app/src/debug/java/com/testappvoxeet/ReactNativeFlipper.java
- in your MainApplication, remove the initializeFlipper (and its implementation)


debug should now work. The test app is still working on my side, I tested it as well with my two side projects apps and they have no issues whatsoever (the fbjni is from my few research a leftover which is... problematic but not used so removing its dependency shouldn't be an issue) and the release should work as well

Please update me with your tests as well. Looking forward to know about it

**Comment by codlab** [comment] 2021-05-23 23:04
@tuneerclixlogix di you have the change to test the latest version ?

**Comment by tuneerclixlogix** [comment] 2021-05-24 05:34
Yes @codlab ,
I think you have removed the following code from your solution from MainApplication.java . But am still using this
`SoLoader.loadLibrary("dvclient");
    SoLoader.loadLibrary("MediaEngineJni");`
After following these steps I haven't faced this crash.

**Comment by codlab** [comment] 2021-05-24 05:42
It's not an issue that you have let those lines (SoLoader will discard them automatically if you are using the latest version)

It's a great news. Given all the devices I have locally, not seeing the crash was a good step in the right direction but knowing that you don't have it anymore as well confirms my suspicions. That's great. I will push new versions quite soon. I am resolving this ticket since the issue no longer exists 👍

**Closed by codlab** 2021-05-24 05:42 UTC
Labels: bug
